//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormUI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FormUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 正在接听！ 的本地化字符串。
        /// </summary>
        internal static string HasBeenAnswering {
            get {
                return ResourceManager.GetString("HasBeenAnswering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 jpg files (*.jpg)|*.jpg 的本地化字符串。
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不存在！ 的本地化字符串。
        /// </summary>
        internal static string Login_NoUser {
            get {
                return ResourceManager.GetString("Login_NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未扫描到该计算机的COM端口，请添加硬件后重新打开程序！ 的本地化字符串。
        /// </summary>
        internal static string NoPort {
            get {
                return ResourceManager.GetString("NoPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        internal static string Num {
            get {
                return ResourceManager.GetString("Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令已发送！ 的本地化字符串。
        /// </summary>
        internal static string OrderSend {
            get {
                return ResourceManager.GetString("OrderSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令失败！请检查串口设备是否已打开。 的本地化字符串。
        /// </summary>
        internal static string Port_Error {
            get {
                return ResourceManager.GetString("Port_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口号不能为空！ 的本地化字符串。
        /// </summary>
        internal static string PortForm_btnOpenClose_Click_ {
            get {
                return ResourceManager.GetString("PortForm_btnOpenClose_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Red.jpg 的本地化字符串。
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        internal static string TerminalForm_GetTerminalList_编号 {
            get {
                return ResourceManager.GetString("TerminalForm_GetTerminalList_编号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示信息 的本地化字符串。
        /// </summary>
        internal static string TipsTitle {
            get {
                return ResourceManager.GetString("TipsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 txt files (*.txt)|*.txt 的本地化字符串。
        /// </summary>
        internal static string WhiteList_Get_txt_files {
            get {
                return ResourceManager.GetString("WhiteList_Get_txt_files", resourceCulture);
            }
        }
    }
}
